<?php

$imagenes = array(
	'Arbol' => dirname(__FILE__).'/png/Arbol.png',
	'Carro' => dirname(__FILE__).'/png/Carro.png',
	'Aeroplano' => dirname(__FILE__).'/png/Avion.png',
	'Bandera' => dirname(__FILE__).'/png/Bandera.png',
	'Cámara' => dirname(__FILE__).'/png/Camara.png',
	'Camión' => dirname(__FILE__).'/png/Camion.png',
	'Camiseta' => dirname(__FILE__).'/png/Camiseta.png',
	'Candado' => dirname(__FILE__).'/png/Candado.png',
	'Carpeta' => dirname(__FILE__).'/png/Carpeta.png',
	'Casa' => dirname(__FILE__).'/png/Casa.png',
	'Computadora' => dirname(__FILE__).'/png/Computadora.png',
	'Clip' => dirname(__FILE__).'/png/Clip.png',
	'Etiqueta' => dirname(__FILE__).'/png/Etiqueta.png',
	'Foco' => dirname(__FILE__).'/png/Foco.png',
	'Gafas' => dirname(__FILE__).'/png/Gafas.png',
	'Gato' => dirname(__FILE__).'/png/Gato.png',
	'Globos' => dirname(__FILE__).'/png/Globos.png',
	'Gráfico' => dirname(__FILE__).'/png/Grafico.png',
	'Hoja' => dirname(__FILE__).'/png/Hoja.png',
	'Hombre' => dirname(__FILE__).'/png/Hombre.png',
	'Impresora' => dirname(__FILE__).'/png/Impresora.png',
	'Lápiz' => dirname(__FILE__).'/png/Lapiz.png',
	'Llave' => dirname(__FILE__).'/png/Llave.png',
	'Lupa' => dirname(__FILE__).'/png/Lupa.png',
	'Mujer' => dirname(__FILE__).'/png/Mujer.png',
	'Mundo' => dirname(__FILE__).'/png/Mundo.png',
	'Nota Musical' => dirname(__FILE__).'/png/Nota Musical.png',
	'Nube' => dirname(__FILE__).'/png/Nube.png',
	'Ojo' => dirname(__FILE__).'/png/Ojo.png',
	'Pantalón' => dirname(__FILE__).'/png/Pantalon.png',
	'Pie' => dirname(__FILE__).'/png/Pie.png',
	'Reloj' => dirname(__FILE__).'/png/Reloj.png',
	'Robot' => dirname(__FILE__).'/png/Robot.png',
	'Silla' => dirname(__FILE__).'/png/Silla.png',
	'Sobre' => dirname(__FILE__).'/png/Sobre.png',
	'Sombrilla' => dirname(__FILE__).'/png/Sombrilla.png',
	'Tijeras' => dirname(__FILE__).'/png/Tijeras.png',
);


?>